

 const recipes = [
   {
    id:1,
    name:"Pancakes",
    image:"https://th.bing.com/th/id/OIP.14ro9tLZ6ncnx802oODMsAHaFb?w=200&h=146&c=7&r=0&o=5&dpr=1.5&pid=1.7",
    cooking_time: "Cooking Time : 10 minutes",
    ingredients: ["1 cup flour","2 tsps baking powder","2 tsps sugar","Pinch of salt","3/4 cup milk","1 egg (beaten)","2 tbsps canola or vegetable oil","2-3 tbsps butter (as a substitute for oil)"],
    method: ["Mixing the Batter: 1.Measure out your dry ingredients.   2.Add milk and an egg 3.Whisk until the batter thickens 4.Let the batter rest for a few minutes", "Preparing Your Cooking Surface: 1.Ready a large griddle or skillet  2.Ready a large griddle or skillet  3.Heat 1tbsp of oil or butter in the skillet 4.Ladle on the pancake batter in small circles." ,
    "Cooking And Serving the Pancakes: 1.Cook the pancakes until they begin to bubble  2.Flip the pancakes over and continue cooking on the other side  3.Remove the pancakes from the heat when they’re golden brown  4.Serve with your favorite toppings"],
   },
   {
    id:2,
    name:"Shakshuka",
    image:"https://th.bing.com/th/id/OIP.VjGcOGlvCKS-lYdrVNfVlAHaHa?w=200&h=200&c=7&r=0&o=5&dpr=1.5&pid=1.7",
    cooking_time: "Cooking Time : 24 minutes",
    ingredients:["Olive oil – 2 tablespoons","Garlic – 3 cloves, minced","Onion – 1 medium, finely chopped",'Bell pepper – 1 large, diced (red or yellow for sweetness)',"Tomatoes – 4 large, diced or 1 can (400g) of diced tomatoes","Tomato paste – 2 tablespoons","Spices: Paprika (1 tsp), cumin (1 tsp), chili powder or cayenne pepper (optional, to taste)","Salt and pepper – to taste","Eggs – 4-6 large",'Fresh parsley or cilantro – for garnish','Optional toppings: Crumbled feta cheese, avocado slices, or toasted bread for serving'],
    method:['Step 1: Prepare the Base.Heat the olive oil in a large skillet over medium heat.Add the chopped onions and sauté until soft and translucent (about 3-4 minutes).Stir in the minced garlic and diced bell peppers. Cook for another 5 minutes, until the peppers soften.',
        'Step 2: Add the Tomatoes and Spices.Add the diced tomatoes and tomato paste to the skillet. Stir well to combine.Sprinkle in the paprika, cumin, and chili powder or cayenne pepper (if using). Season with salt and pepper to taste.Reduce the heat to low and let the sauce simmer for 10 minutes, stirring occasionally, until it thickens slightly.',
        'Step 3: Poach the Eggs.Use a spoon to make small wells in the sauce for the eggs.Crack an egg into each well, being careful not to break the yolk.Cover the skillet with a lid and cook for 5-8 minutes, or until the egg whites are set but the yolks remain runny (or cook longer for firmer yolks).',
        'Step 4: Garnish and Serve.Remove the skillet from the heat and sprinkle fresh parsley or cilantro over the top.Optional: Add crumbled feta cheese or avocado slices for extra flavor.Serve hot with toasted bread, pita, or a side salad.'],
   },
   {
    id:3,
    name:"Chole Bhature",
    image:"https://th.bing.com/th/id/OIP.sieaLp7JHGSAG_DAqKw9KQHaE7?w=266&h=180&c=7&r=0&o=5&dpr=1.5&pid=1.7",
    cooking_time:"Prep-time:8-10hr, Cooking time: 50-60 minutes",
    ingredients:["For chole:2 cup Chickpeas","2 tsp Oil","1 Bay leaf","1 Cinnamon stic","3-4 Cloves","1 tsp Whole pepper corns","3 Green cardamom","2 Black cardamom","1 tsp Turmeric powder","1 tsp Chilli powder","1 tsp Coriander powder","1 tsp Cumin" , "tsp Cumin seeds", "1/2 tsp Asafoetida","to taste Salt","1 cup Onions", "chopped1 cup Tomatoes", "chopped1 tsp Ginger", "chopped1 tsp Garlic", "chopped1 tsp Ajwain","1 tsp Lime juice","1 Green chili"," chopped1 Tea bag","1 tbsp Butter","For the bhaturas:2 cups Refined flour","1/2 tsp Yeast (dissolved for 10 minutes in luke warm water)","1/2 cup Whole wheat flour","A pinch of SaltWater (to knead)","Oil (for frying)"],
    method:["To prepare chole: In a pan add oil, bay leaf, cinnamon, cumin seeds, cloves, whole pepper corns, green and black cardamom.","1.After it browns, add chopped onions and saute. Add chopped ginger and garlic.", "2.Now, add turmeric, chili powder, coriander powder, cumin powder, asafoetida and salt. Fry the ingredients together.","3.For de-glazing the pan, add a little water.","4.Now, add the chole (soaked overnight and pressure cooked) to the masala.","5.After stirring well, add tomatoes, a little sugar and salt to the chole.","6.Now, add ajwain, chopped green chilies and water for the base.","7.To get the color in the chole, add a tea bag to the masala.","8.Simmer the chole gently for an hour and cover it.","9.Add lime juice and a dollop of butter to it.","10.Garnish the chole with coriander and butter and serve them hot with bhaturas."],
   },
   {
    id:4,
    name:"Croissant Sandwich",
    image:"https://th.bing.com/th?id=OIF.3cqyzPxh4vJkMNtrsUe%2fJw&w=198&h=198&c=7&r=0&o=5&dpr=1.5&pid=1.7",
    cooking_time:"prep-time:10 minutes",
    ingredients:["1 large, flaky croissant","2-3 slices of your favorite deli meats (turkey, ham, or roast beef)", "1-2 slices of cheese (Swiss, cheddar, or provolone are great options)", "Fresh lettuce or baby spinach","Ripe tomato slices","Condiments like Dijon mustard or mayo]"],
    method:["Split a fresh croissant lengthwise.","Spread your favorite condiments on both halves.","Layer cheese on the bottom half.", "Add meat, folding it for extra volume.", "Top with fresh veggies like crisp lettuce and juicy tomato slices.", "For extra crunch, add bacon or chips.", "Close the sandwich with the top croissant half."],
   },
   {
    id:5,
    name:"Scrambled Eggs And Chciken Sausages",
    image:"https://th.bing.com/th/id/OIP.zqKywkNBzcsF2Tgge3CPIAHaE8?w=286&h=191&c=7&r=0&o=5&dpr=1.5&pid=1.7",
    cooking_time:"Cooking-time: 25 minutes",
    ingredients:["4 chicken sausages", "2 tablespoon refined oil","salt as required","3 leaves coriander leaves","6 egg","1/4 cup cheese-cheddar","black pepper as required"],
    method:["Step 1 Scramble the eggs.Take a pan and add some oil to it. Let this oil heat and add in the eggs. Then add in some grated cheese, mix well and season the cheesy eggs with salt and pepper. Then take them out on a plate.",
        "Step 2 Toss the sausages and serve.To the same pan, add the sausages toss them in oil for 4-5 minutes or until they brown. Then turn off the flame and transfer the sausages to the plate. Lastly, garnish with coriander leaves and and serve hot!"
    ],
         
    },
   {
    id:6,
    name:"Rawa Upma",
    image:"https://th.bing.com/th/id/OIP.YQngmjlVvmCnDmDutPjxZwHaFL?w=200&h=207&c=7&r=0&o=5&dpr=1.5&pid=1.7",
    cooking_time:"Cooking-time: 20 minutes",
    ingredients:["1 cup semolina", "1 dry red chili", "1/2 onion", "1/2 teaspoon sliced ginger"," 1 teaspoon urad dal", "1 stalk curry leaves", "1 teaspoon mustard seeds","1/4 teaspoon asafoetida","1/2 carrot","salt as required","2 tablespoon vegetable oil", "2 1/2 cup water"],
    method:["Step 1: Saute the ingredients:Heat oil in a pan. Add asafoetida, sliced ginger, dry chilli and curry leaves. Saute for a minute. Now add mustard seeds and let them splutter. Now add urad dal and fry it for a few minutes.",
           "Step 2 Saute the veggies: Now add chopped onion and let them cook until translucent. Add chopped carrot and cook it for a few minutes.",
           "Step 3 Cook the upma: Add the rava and roast it for a few minutes. Now add water, salt and continuously stir the mixture. Once it starts thickening, keep the flame medium and stir it.",
           "Step 4 Ready to be served: Once the rava absorbs all the water and the upma becomes thick, it is ready to be served. Enjoy it with coconut chutney."],
   },
   {
    id:7,
    name:"Spanish Omlette",
    image:"https://th.bing.com/th/id/OIP.wieIkfKD9NOMt1M7ncIW0AHaHa?w=200&h=200&c=7&r=0&o=5&dpr=1.5&pid=1.7",
    cooking_time:"Cooking-time: 10-15 minutes",
    ingredients:["1 Tbsp olive oil","1 tsp butter","1 onion sliced","1 potato sliced","5 eggs","to taste pepper","to taste salt","2 tsp parsley + to garnish chopped"],
    method:["In a pan add olive oil and butter.","2.Add onions, saute till pink.","3.Add thinly sliced potatoes. Saute for 3-4 minutes.","4.In a bowl whisk eggs with a little parsley, salt and pepper.","5.Mix the onion-potato mixture into the eggs.","6.Pour the omelette batter in the same saucepan and cook for 3-4 minutes.","7.Flip and cook from the other side.8.Garnish with parsley. Serve."],
   },
   {
    id:8,
    name:"Simit",
    image:"https://th.bing.com/th/id/OIP.mzLvOJnWJkJOThVZVz0OSQHaFq?w=250&h=191&c=7&r=0&o=5&dpr=1.5&pid=1.7",
    cooking_time:"Cooking-time: 1 hour",
    ingredients:["flour","Yeast","Salt","Sugar","Water","Olive oil","Sesame Seeds","Molasses"],
    method:["Prepare The Dough:1- Start by placing the flour, yeast, salt and sugar in a stand mixer bowl. Add in warm water and vegetable oil. Make sure the water is not too hot or too cold. The water you use to make bread should be warm to touch.",
            "2- Mix using the dough hook until the dough comes together and is a little sticky. If the dough is too sticky and sticks to the bowl, start adding the 5th cup of flour one tablespoon at a time. You will probably need only 2 or 3 tablespoons of flour so make sure not to add a lot of flour.",
           " 3- Once the dough has come together and is a little sticky, it’s time to knead the dough. Knead the simit dough using a dough hook for about 8 minutes until it’s not sticky anymore.",
           " 4- Cover the bowl with plastic wrap and a towel. Place it in a draft-free space such as an off oven and let it rise for 1.5 hours until it’s doubled in size. ",
          " Shape The Simit:5- After 1.5 hours, check on the simit dough which must have doubled by now. Carefully punch in down and knead it for a few seconds. Divide the dough into 16 pieces.",
           "6- Roll out two of the dough pieces into 25 inch tubes each and place them parallel to each other.",
            "7- Pinch the ends and roll the tubes in opposite directions to make a twist (check out the step-by-step photos). Meet and pinch the ends on both sides together to form a circle.",
          "8- Repeat with the remaining 14 pieces to make 7 more simits. An alternative method would be to divide the dough into 8 pieces and roll out to have a 40-45 inch tube, then fold it and twist it. ",
        "Final Touches And Bake:9- Toast the sesame seeds and in a shallow and wide dish (like a pie dish) whisk together the molasses and water. Dip each twisted dough in the molasses and water combination and make sure it’s covered on both sides.",
        "10- Dip the simit in toasted sesame seeds and ensure they are fully coated on all sides.",
        "11- Place them on a baking sheet lined with parchment paper. Let the dough circles rest for another 20 minutes. Meanwhile, preheat the oven to 400 degrees F.",
        "12- Bake the simits in the oven for 12-15 minutes until they are golden brown and fully baked. ",
        ],
   },
   {
    id:9,
    name:"Steamed Bao Buns",
    image:"https://th.bing.com/th/id/OIP.R2RqKR-09S01-_27Psz7aQHaHa?w=195&h=195&c=7&r=0&o=5&dpr=1.5&pid=1.7",
    cooking_time:"Cooking-time: 1 hour 35 minutes",
    ingredients:["250 gm all purpose flour","1/2 teaspoon dry yeast","1 tablespoon sunflower oil","1/2 teaspoon baking powder","1/2 tablespoon caster sugar","25 ml lukewarm milk","1/2 tablespoon rice vinegar"],
    method:["Step 1 Mix the dry ingredients:Take a bowl, add flour, caster sugar and salt to it. Mix the dry ingredients well.",
        "Step 2 Prepare the dough:Dissolve the yeast in 1 tbsp warm water. Now add it to the flour along with the milk, sunflower oil, rice vinegar and water. Knead to form a soft dough. Cover with a damp cloth and let it rest for an hour.",
        "Step 3 Add baking powder:After an hour, add baking powder and knead it again for a few minutes.",
        "Step 4 Make small balls and roll them out.Now divide the dough into equal parts and make small balls. Use a rolling pin to flatten them out. Make small ovals with a medium thickness.",
        "Step 5 Leave them to rest:Now grease the sides of the ovals and fold them gently into halves. Let them rest in a warm place for an hour. This will make the buns double in size.",
        "Step 6 Steam the buns: Now put the buns in a steamer and steam them for 8-10 minutes.",
        "Step 7 Stuff and serve: Your buns are ready to be stuffed. Stuff them with a filling of your choice or if you wish to go the traditional way, stuff them with barbeque pork and pickled carrots. Enjoy the classic Chinese dish."],
   },
   {
    id:10,
    name:"Korean Chicken Porridge",
    image:"https://th.bing.com/th/id/OIP.Di6YBZd3NvDmjPT-8ujVpgHaE7?w=232&h=180&c=7&r=0&o=5&dpr=1.5&pid=1.7",
    cooking_time:"Cooking-time:50 minutes",
    ingredients:["1 cup short-grain rice (or sweet rice glutinous rice)", "6 cups chicken stock (use a good quality or homemade stock for best flavor)", "1 1/2 cups shredded chicken (salt, garlic, sesame oil, pepper, for example)", "1 medium carrot", "1 stalk celery", "2 mushroom caps (shiitake)", "2 tablespoons sesame oil", "1 scallion, finely chopped","1 teaspoon sesame seeds"],
    method:["Soak the Rice: Soak the rice for at least 1 hour to allow it to rehydrate.",
        "Prepare the Vegetables: Finely chop the carrot, celery, and mushroom caps.",
        "Heat the Broth: Pour the chicken stock into a large pot and bring to a boil.",
        "Add the Rice: Add the soaked rice to the pot and stir to combine with the broth.",
        "Reduce Heat: Reduce the heat to medium-low and simmer for 20-25 minutes, stirring occasionally, until the rice is cooked and softened.",
        "Add Vegetables: Stir in the chopped vegetables and continue to simmer for an additional 10-15 minutes, until the vegetables are soft.",
        "Add Chicken: Stir in the shredded chicken and cook for an additional 2-3 minutes, until heated through.",
        "Season: Taste and adjust seasoning with salt and pepper as needed.",
        "Serve: Serve hot, garnished with scallions and sesame seeds."],
   },
   {
    id:11,
    name:"Dosa",
    image:"https://th.bing.com/th/id/OIP.qT5QyXTbjIh3XltVJKXtJQHaE8?w=248&h=180&c=7&r=0&o=5&dpr=1.5&pid=1.7",
    cooking_time:["Preparation Time:  14 hours ","Cooking Time:  25 minutes"],
    ingredients:["3/4 cup Parboiled Rice (idli-dosa rice)", "3/4 cup Regular Rice", "1/2 cup Whole Urad Dal (without skin) or Split Urad Dal (black lentils)", "1/4 teaspoon Fenugreek Seeds (methi dana)", "1/2 tablespoon Chana Dal (gram lentils), optional","Water, as needed", "Salt to taste","Oil, for shallow frying"],
    method:["Making the Batter:Soak the rice.",
        "Soak the urad dhal and fenugreek .Grind the urad dhal and fenugreek.Grind the rice.Combine the rice batter and the urad dhal.Allow the batter to ferment.Check the batter. Refrigerate the batter until you are ready to cook.",
        "Preparing to Cook:Bring the batter to room temperature.Heat the cooking surface.Heat the cooking surface.",
        "Decide what size you want to make your dosas.",
        "Cooking the Dosas:Spread the batter,",
        "Allow the batter to cook.Flip the dosa if desired,Lift the dosa off of the cooking surface.Fold the dosa while it is still hot.Repeat the process.", 
    ],
   },
   {
    id:12,
    name:"Fara",
    image:"https://th.bing.com/th/id/OIP.Fozb3TEEje3_CKBIxujB5gHaFj?w=241&h=181&c=7&r=0&o=5&dpr=1.5&pid=1.7",
    cooking_time:"Cooking-time: 20 minutes",
    ingredients:["Rice Flour	1 cup", "Green Chilies	2, finely chopped", "Ginger	1-inch piece, grated","Cumin Seeds	1 teaspoon", "Mustard Seeds	1 teaspoon", "Asafoetida (Hing)	1/4 teaspoon","Oil	2 tablespoons","Salt	To taste","Water	As needed"],
    method:["Prepare the Dough: In a mixing bowl, combine rice flour, chopped green chillies, grated ginger, cumin seeds, mustard seeds, asafoetida, 2 tablespoons of oil, and salt. Gradually add water and knead the mixture into a smooth dough.",
        "Roll the Dough: Take small portions of the dough and roll them into cylindrical shapes.",
        "Steam Fara: Place the cylindrical dough pieces in a steamer and steam for about 15-20 minutes until they are cooked through.",
        "Cool and Slice: Allow the steamed fara to cool. Then, slice them into rounds.",
        "Temper with Spices: Heat some oil in a pan, add cumin seeds, and as the seeds splutter, add the sliced fara rounds. Sauté them until they turn slightly golden and crisp.",
        "Serve Hot: Your Fara is ready to be served hot. Enjoy them with chutney or a side of your choice."],
   },
   {
    id:13,
    name:"Paya Nihari",
    image:"https://th.bing.com/th/id/OIP.m-e3HpyP5PTNzkAszop3HQHaFt?w=259&h=200&c=7&r=0&o=5&dpr=1.5&pid=1.7",
    cooking_time:"Cooking-time:1-2 hours",
    ingredients:["Nalli/Paya/ Lamb leg pieces	4  paya or 1/2 kg","4 onions for boiling with nalli , 1 for grind, 2 for frying", "Ginger-garlic paste",	"2 teaspoon", "Turmeric powder	1/2 teaspoon for boiling lamb and 1/2 teaspoon for spice",
        "Salt	to taste","Mustard oil	3/4 cup","Bay leaf	2","Cinnamon stick	1/2 inch piece","Tomato	1","Cumin seeds	1 teaspoon","Cardamom green	2","Cardamom brown	1",
        "Cloves	5","Nutmeg	small pinch","Mace	1/4 teaspoon","Black pepper	1/2 teaspoon","Red chilly powder	1 teaspoon","Coriander powder	for garnish"],
    method:["1. Clean, wash the lamb leg pieces. Take pressure cooker and add lamb leg pieces, diced onion, turmeric powder, 1/2 teaspoon salt, 1/4 cup mustard oil, 1 teaspoon ginger-garlic paste and 1 –1/2  glass of water. Close the lid and pressure cook it on high heat for one whistle then low the flame and cook for another 45 minutes. Switch off the flame and let the pressure settles down.",
        "2. Open cooker and mash the onion with spatula. You will feel the gravy is thick enough. Keep it aside. Grind cumin seeds, black pepper, cloves, cardamom green, cardamom brown, Mace, nutmeg, 1 teaspoon ginger-garlic paste (I used my homemade ginger-garlic paste), 1 diced onion, cinnamon stick along with 2 tablespoon water to make fine paste.",
        "3. Heat the non stick pan with remaining 1/2 cup oil and temper with bay leaf.",
        "4. Add chopped onions in the pan and fry it till light golden in color. Add ground paste in the wok.",
       " 5. Add chopped tomato, red chilly powder, turmeric powder, coriander powder and salt. Cook the spices on low flame till oil shows separately.",
       " 6. Add cooked spices into the pressure cooker along with a glass of water. Mix it well. Check salt, if needed add more salt. Pressure cook it for one whistle on high flame, then cook for another 10 minutes on low flame. Switch off the flame, let the pressure settle down. Garnish with coriander leaves. Serve hot with chapatti, kulcha, naan etc.",
        "7. Enjoy!!"],
   },
   {
    id:14,
    name:"French Toast",
    image:"https://th.bing.com/th/id/OIP.Wr_9gEXsC7eRv6nwh-7LVgHaHa?w=200&h=200&c=7&r=0&o=5&dpr=1.5&pid=1.7",
    cooking_time:"Cooking Time:15 mins",
    ingredients:["4 large eggs","2/3 cup milk","2 teaspoons cinnamon", "8 thick slices 2-day-old bread (better if slightly stale)","Butter (can sub vegetable oil)","Maple syrup"],
    method:["1.Make the egg mixture: In a medium bowl, whisk together the eggs, milk, and cinnamon. Stir in the orange zest and/or triple sec if using. Whisk the mixture until well blended and pour into a shallow bowl, wide enough to place a slice of the bread you will be using.",
     "2.Soak the bread slices in egg mixture:Place each slice of bread into the milk egg mixture, allowing the bread to soak in some of it.",
    " 3.Fry the French toast:Melt some butter in a large skillet over medium high heat. Shake off the excess egg mixture from the bread and place the bread slices onto the hot skillet. Fry the French toast until browned on one side, then flip and brown the other side.",
    "4.Serve:Serve the French toast hot with butter, maple syrup, and/or fresh berries."],  
},
   {
    id:15,
    name:"Oatmeal",
    image:"https://th.bing.com/th?id=OIF.cuaua6mPB6tWu%2fNan2qw9g&w=198&h=264&c=7&r=0&o=5&dpr=1.5&pid=1.7",
    cooking_time:"Cooking-time:5-10 mintues",
    ingredients:["Old-fashioned rolled oats: This recipe calls for old-fashioned rolled oats, which cook faster than steel-cut oats, absorb more liquid, and hold their shape relatively well during cooking. ",
        "Water: You’ll need 3 cups of water.",
        "Toppings (optional): Use your favorite toppings, like honey, maple syrup, or brown sugar."],
    method:["1.Bring the water to a boil first. You want a three-to-two ratio of water to rolled oats. Bringing the water to a boil before you add the oats keeps them from absorbing too much water.",
        "2.Add the oats at a simmer. Once boiling, drop the temp down to a gentle simmer and add the oats. Simmer for three minutes, stirring here and there. Then shut off the heat and move the pot off the burner.",
        "3.over and rest for five minutes. This is where the magic happens: Let the oats absorb the water without stirring or simmering. Perfect oatmeal is just ahead, so get your toppings ready."
        ],
   },
   {
    id:16,
    name:"Idli",
    image:"https://th.bing.com/th/id/OIP.gHemYRQdRCmFb6-06XZrZAHaE8?w=260&h=180&c=7&r=0&o=5&dpr=1.5&pid=1.7",
    cooking_time:"prep-time:8-12 hours, cooking-time:10-15 minutes",
    ingredients:["2 1/2 cup basmati rice","1/2 tablespoon fenugreek seeds","5 tablespoon sesame oil", "1 1/2 cup urad dal","salt as required", "water as required"],
    method:["Step 1 Soak the rice & dal and grind into a paste & combine:To prepare this popular South Indian recipe, wash rice and urad dal separately until the water runs clean and add fenugreek seeds to the rice. Soak it in water for 4-6 hours. Soak the urad dal too for the same amount of time. Drain all the water from the urad dal and grind it to a fine paste. Add water accordingly. Grind the rice to a coarse paste (add water as needed) and then mix both the pastes together in a large bowl and whisk them well. Make sure that the consistency is thick.",
          "Step 2 Let the batter ferment, then add salt: Now, the idli batter needs to be well-fermented. This step is very important to get soft and fluffy idlis. Keep the batter in a warm place to ferment. Once the batter has risen, add salt to it and whisk to mix it well.",
          " Step 3 Transfer the idli batter in the idli stand: Grease the idli stand with oil and take a ladleful of batter and fill the idli mould. Add ½ cup of water in the idli steamer and let it boil. Put the idli stand inside and close the lid. Let the steam build for 8-10 minutes before switching off the gas.",
          " Step 4 Wait for the utensil to cool a bit before scooping the idlis out: If you are using a cooker, use it without a vent and steam it for 10 minutes and then switch the gas off. In both cases, wait till the steam is released before you take the idli stand out. Wait for another 5 minutes and then use a sharp knife to scoop the idlis out. Serve warm with coconut chutney and sambhar."],
   },
   {
    id:17,
    name:"Rajma Chawal",
    image:"https://th.bing.com/th/id/OIP.FhN9PML6Bib60yHDp02xLgHaEK?w=283&h=180&c=7&r=0&o=5&dpr=1.5&pid=1.7",
    cooking_time:"Prep-time: 20 minutes, Cooking-time: 30 minutes",
    ingredients:["1 cup Rajma (kidney beans)"," 1 tbsp Oil", "1 Bay leaf", "1 Cinnamon stick", "2 Black cardamom", "3-4 Cloves", "3-4 Black peppercorns", "1 Onion, finely chopped",
        "1 tbsp Ginger-garlic paste","2 Green chilies, finely chopped","2 Tomatoes, finely chopped"," 1 tbsp Tomato purée","1 tsp Cumin seeds", "1 tsp Coriander powder", "1 tsp Red chili powder","1/2 tsp Turmeric powder","1 tbsp Kasuri methi (dried fenugreek leaves)",  "Salt to taste","Fresh coriander leaves for garnish"],
    method:["1.  Soak the Rajma: Soak 1 cup of rajma (kidney beans) in water overnight or for at least 8-10 hours. This helps in softening the beans and reduces cooking time. A bowl of rajma (kidney beans) soaking in water overnight, preparing for the cooking process.",
            "2.  Cook the Rajma:Drain the soaked rajma and add it to a pressure cooker. Add 1 bay leaf, 1 cinnamon stick, 2 black cardamom, 3-4 cloves, 3-4 black peppercorns, and salt. Add enough water to cover the beans. Close the lid and cook for 5-6 whistles or until the beans are tender.Rajma beans with whole spices in a pressure cooker, ready to be cooked until tender.",
           "3.  Prepare the Masala: Heat 1 tbsp oil in a pan. Add 1 tsp cumin seeds and let them splutter. Add finely chopped onions and sauté until they turn golden brown. Add 1 tbsp ginger-garlic paste and finely chopped green chilies. Sauté for another 2-3 minutes.Onions sautéing in a pan with cumin seeds and ginger-garlic paste, forming the base for the masala.",
            "4.  Add Tomatoes and Spices:  Add finely chopped tomatoes and cook until they soften. Add 1 tbsp tomato purée and mix well. Add 1 tsp coriander powder, 1 tsp red chili powder, and 1/2 tsp turmeric powder. Cook the mixture until the oil starts to separate from the masala. Tomatoes and spices being added to the pan, creating a rich and flavorful masala.",
            "5.  Combine Rajma and Masala:Add the cooked rajma along with its water to the masala. Mix well and let it simmer on low heat for 15-20 minutes. Adjust the consistency by adding more water if needed.Cooked rajma being mixed with the masala in the pan, allowing flavors to meld together.",
            "6.  Final Touches: The finished rajma dish garnished with fresh coriander leaves, ready to be served with steamed rice. Crush 1 tbsp kasuri methi (dried fenugreek leaves) and add to the rajma. Stir well and let it cook for another 5 minutes. Garnish with fresh coriander leaves.",
        
         ],
   },
   {
    id:18,
    name:"Kimbap",
    image:"https://th.bing.com/th/id/OIP.AUwdvH2qzNaDFVnTe_E6PgHaE6?w=285&h=189&c=7&r=0&o=5&dpr=1.5&pid=1.7",
    cooking_time:"Cooking Time : 30-40 mins",
    ingredients:["Seafood sticks", "Smoked Salmon", "Tuna (tined, seasoned with black pepper and mayonnaise)", "Cucumber", "Carrot", "Courgette (zucchini)", "Mushroom", "Spinach (boiled, seasoned with salt, sesame oil and soy sauce)", "Eggs - Make into a thin omelette and slice"],
    method:["Step 1: Gather all the ingredient:Before starting, gather all the necessary ingredients and equipment for making kimbap.",
           "Step 2: Cook the rice:  Rinse the short grain rice and cook it according to the package instructions.",
           "Step 3: Season the rice: Transfer the cooked rice to a large mixing bowl and season it with sesame oil and salt. Mix well to coat every grain of rice.",
           " Step 4: Prepare the bee: Thinly slice the beef and marinate it in a mixture of soy sauce, sesame oil, minced garlic, and sugar. Cook the marinated beef until fully cooked and slightly caramelized.",
           "Step 5: Prepare the fish cake:Thaw the frozen fish cake slices and cut them into thin strips.",
           "Step 6: Cook the eggs:Beat the eggs and cook them into thin omelets. Slice the cooked omelets into thin strips.",
           "Step 7: Prepare the carrots:Peel the carrots and cut them into thin matchstick-like pieces. Blanch the carrots in boiling water until slightly softened.",
           "Step 8: Prepare the spinach: Blanch the spinach in boiling water for a short time, then transfer it to ice water. Drain the spinach and season it with sesame oil and salt.",
          " Step 9: Prepare the burdock root :Peel the burdock root and cut it into thin matchstick-like pieces. Blanch the burdock root in boiling water until tender.",
          " Step 10: Assemble the Kimbap: Place a bamboo rolling mat on a clean surface. Place a sheet of dried seaweed on the mat, shiny side down. Spread the seasoned rice evenly on the seaweed, leaving a small border. Arrange the filling ingredients in a line across the center of the rice.",
          "Step 11: Roll the kimbap tightly: Using the bamboo mat, start rolling the kimbap away from you, applying gentle but firm pressure. Lift the bamboo mat as you roll, ensuring a tight and compact roll. Seal the edge of the seaweed with a small amount of water.",
           "Step 12: Slice and serve: Once rolled, use a sharp knife to slice the kimbap into bite-sized pieces. Serve and enjoy!",
           "Now that you have all the necessary information and step-by-step instructions, it’s time to embark on your kimbap-making journey. Have fun experimenting with different fillings and enjoy this delicious and satisfying Korean dish!",
        ],
   },
   {
    id:19,
    name:"Frittata",
    image:"https://th.bing.com/th/id/OIP.oXyFtiz_7RfoFUIE5WgpRQHaHa?w=200&h=266&c=7&r=0&o=5&dpr=1.5&pid=1.7",
    cooking_time:"Cooking Time : 25-35 mins",
    ingredients:["Bacon","Fresh spinach","Grape tomatoes","Eggs","Half and half","Onion powder and garlic powder","Salt and pepper","Swiss cheese"],
    method:["Preheat oven to 350 degrees. Butter a 9 – 10 inch deep pie dish, set aside.",
        "Place bacon in a 12-inch non-stick skillet and cook over medium-high heat, tossing frequently, until browned and crisp, about 6 – 10 minutes.",
        "Transfer bacon to a plate lined with several layers of paper towels to drain, leave 1 Tbsp rendered bacon fat in a skillet drain and reserve or discard excess.",
        "Sauteeing bacon in a large black skillet to make a frittata.",
         "Return skillet to medium-high heat, add spinach and saute just briefly until it has wilted, about 15 seconds, transfer spinach to plate with bacon. Sauteeing spinach in a large skillet to add to frittata.",
        "In a large mixing bowl whisk together eggs, half and half, onion powder, garlic powder until well combined.",
        "Season with salt and pepper to taste (season lightly with salt as the bacon and cheese will add salt. I only needed about 1/4 tsp salt).",
         "Add cooked bacon, spinach and Swiss and toss mixture to distribute ingredients. Pour into prepared pie dish.",
        "Bake in preheated oven until just set, about 30 – 35 minutes. Cut into wedges and serve warm."],
   },   
    {  
    id:20,
    name:"Falafel With Tahini",
    image:"https://th.bing.com/th/id/OIP._qBrVTnid_4ELgyUHLp_KgHaF7?w=230&h=184&c=7&r=0&o=5&dpr=1.5&pid=1.7",
    cooking_time:"Prep Time: 45 minutes ,Cook Time: 16 pieces (approximately 2-3 minutes per piece)",
    ingredients:["1 teaspoon cumin seed", "1/2 teaspoon coriander seed", "1/4 teaspoon fenugreek seeds (optional, but recommended)", "1/4 teaspoon red chili pepper flakes", "2 cups cooked chickpeas (canned or cooked in pressure cooker)",
        "1/2 cup chopped white onion","3 medium garlic cloves","1/4 cup white sesame seeds", "1 cup matzo meal", "1 cup chopped flat leaf parsley", "1 teaspoon baking powder",
        "2 eggs","1 teaspoon salt (use less if the chickpeas are salted)","1/2 teaspoon fresh ground black pepper","1 quart oil (for frying)","1/4 cup tahini","1/4 cup garlic clove", "1/2 teaspoon cumin seed, toasted and ground",
        "1/2 teaspoon fennel seed, toasted and ground", "1/4 teaspoon salt", "Juice of half a small lemon", "1/4 teaspoon red chili powder (or 1/4 teaspoon cayenne)", "2 tablespoons water"],
    method:["Step 1: Prepare the Falafel,Grind the cumin seed, coriander seed, and fenugreek seeds in a spice grinder or mortar and pestle.Place the ground spices in the workbowl of a food processor along with the chickpeas, onion, and garlic. Pulse several times to mince the contents. Add the sesame seeds, matzo meal, parsley, and baking powder and pulse until evenly mixed.Beat the egg in a large bowl, add the chickpea mixture, salt, and pepper, and mix well. Chill at least 15 minutes.",
        "Step 2: Form the Falafel, Form 16 balls of the chilled chickpea mixture and place on a parchment-lined baking sheet, flattening each ball slightly.Heat the oil to 360°F in a large heavy pot and fry the falafel until golden, turning at least once. This should take 2 or 3 minutes. Drain well before serving.",
        "Step 3: Prepare the Tahini Sauce: Combine all ingredients except water in the workbowl of a food processor and pulse until smooth. Add the water slowly with the motor running until it forms a creamy sauce"],
   },
   {
    id:21,
    name:"Club Sandwich",
    image:"https://th.bing.com/th/id/OIP.1l-4XyVzjwceAoQgpom_qgHaH-?w=178&h=193&c=7&r=0&o=5&dpr=1.5&pid=1.7",
    cooking_time:"Cooking time : 15-20 mins",
    ingredients:["2-3 slices of white bread",  "2-3 strips of bacon",  "Mayonnaise","Sliced chicken or turkey breast","Sliced tomato","Lettuce","Salt and pepper (to taste, optional)"],
    method:[
        "1.Fry 2-3 slices of bacon until they’re crisp",
        "2 Toast 3 slices of white sandwich bread.",
        "3 Spread mayonnaise on 1 slice of bread.4.Layer on the sliced chicken or turkey. ",
        "4.Top off the first layer with some lettuce and tomato. ",   
        "5.Add another slice of bread and mayo.",
        "6.Place the bacon on the second layer of bread.", 
        "7.Add another layer of chicken or turkey, tomato, and lettuce.",
        "8.Top the sandwich with the final piece of toasted bread",
        "9.Cut the sandwich along both diagonals. ",
        "10.Serve your sandwich with chips or fries in the middle of the plate",
    ],
   },
   {
    id:22,
    name:"Chickpea Salad",
    image:"https://th.bing.com/th/id/OIP.1xzpDxVoGQr_869f259Y7gHaLG?w=200&h=300&c=7&r=0&o=5&dpr=1.5&pid=1.7",
    cooking_time:"Prep Time : 10-15 mins",
    ingredients:["Chickpeas", "Avocado", "Cherry Tomatoes", "Cucumber", "Bell Pepper",  "Red Onion", "Parsley", "Lemon Juice", "Lemon Dressing – The bright lemon dressing makes this dish pop! Use olive oil, lemon juice, garlic clove, Dijon mustard, honey, salt, and pepper. For a vegan version, use maple syrup instead of honey." ],
    method:["1. Mix the salad ingredients. Just toss it all in a big bowl with the lemon juice.","2. Make the dressing. Whisk everything until well blended.",
          "3. Dress and rest the salad. Toss the salad with the dressing then let it sit for about 10 minutes.","4. Stir and serve. Stir again and serve."],
   },
   {
    id:23,
    name:"Tuna Wrap",
    image:"https://th.bing.com/th/id/OIP.BNqnL_6qwvdgJ-cizF4yKwHaJQ?w=128&h=180&c=7&r=0&o=5&dpr=1.5&pid=1.7",
    cooking_time:"Prep Time: 10 mins",
    ingredients:["Tuna","Crunchy vegetables", "mayonnaise", "mustard", "lettuce", "spinach tortillas"],
    method:["Step 1: Make the tuna salad Drain the tuna, and add it to a small bowl. Add the celery, green onion, water chestnuts and bell pepper. Spoon in the mayonnaise and mustard, then stir everything together until the mixture is well combined.",
        "Step 2: Assemble the wraps Spread the tuna salad over two tortillas, and sprinkle with lettuce.",
        "Roll up tightly jelly-roll style."],
   },
   {
    id:24,
    name:"Dal Makhani",
    image:"https://th.bing.com/th/id/OIP.30QBv2VFnM_0ytUfC3TicgHaJQ?w=155&h=194&c=7&r=0&o=5&dpr=1.5&pid=1.7",
    cooking_time:"Prep Time : 10 mins, Cooking Time : 40 mins",
    ingredients:["2 Cups sabut urad dal","8 cups water","2 tbsp salt","1 tbsp ginger sliced", "2 tbsp butter","1 tbsp oil","2 tsp shahi jeera","1 tsp kasoori meethi","2 cups tomato puree","1 tsp chilli powder","1 tsp sugar","1/2 cups creamfor garnishing","green chillies (slit lengthwise)"],
    method:["1.To the dal, add water, 1 Tbsp salt and ginger. Cook until dal becomes tender.","2.In a heavy based pan, heat butter and oil. Add shahi jeera and kasoori methi. When they begin to splutter, add tomato puree, remaining salt, chilli powder and sugar.","3.Stir-fry over high flame, till the oil separates.","4.Add cooked dal and bring to boil. The consistency should be such that the dal should move around freely when stirred, otherwise add a little water.","5.Leave to simmer, uncovered, till well blended. Stir-in cream and once it gets heated through, serve immediately, garnished with green chillies"],
   },
   {
    id:25,
    name:"Kathi Roll",
    image:"https://th.bing.com/th/id/OIP.B4yDpakujsWcsU0XVQ_YIwHaFA?w=233&h=180&c=7&r=0&o=5&dpr=1.5&pid=1.7",
    cooking_time:"Cooking time : 30-40 mins",
    ingredients:["1/2 cup wheat flour", "1/4 cup capsicum (green pepper)", "1/2 tablespoon mustard oil", "1 pinch asafoetida","1/4 teaspoon garlic paste","1/4 teaspoon coriander powder",
        "1 pinch powdered turmeric","2 leaves coriander leaves", "1/2 potato", "1/4 cup tomato", "1/4 teaspoon cumin", "1/2 onion", "1/4 teaspoon garam masala powder","red chilli powder as required", "salt as required", "1 tablespoon green chutney"],
    method:["Step 1 Knead a smooth dough: Kathi Roll is one of the easiest recipes to prepare at home. Here’s how you prepare this scrumptious snack recipe. First, you need to prepare the dough., Take a dough kneading plate and add wheat flour in it along with a little salt. Mix well and then add water in batches to knead a soft and smooth dough. Once the dough is ready, cover with a damp cotton cloth and keep it aside till required.",
        "Step 2 Pressure cook the potatos & chop the veggies: Afterwards, put a pressure cooker on high flame and add potato in it along with enough water to submerge the potato in it. Close the lid of the cooker and cook for 2 whistles. Once cooked, let the steam release on its own and then drain the extra water and peel the potato in a bowl, mash it using a masher. Now, wash tomato and capsicum in running water and finely chop them in separate bowls. Peel the onion and thinly slice it in a bowl, keep aside till required.",
        "Step 3 Saute the onion: Put a non-stick pan on medium flame and heat oil in it. Once the oil is hot enough, add cumin and mustard seeds in it, when they start to crackle, add a pinch of asafoetida along with salt. Saute for a few seconds and then add the onions in it. Saute the onions until translucent and pink in colour.",
       " Step 4 Cook veggies in ginger garlic paste & spices:Now, add garlic paste in the pan and saute for a minute, and quickly add capsicum along with tomato in the pan. Stir to mix all the spices and then add mashed potato in it. Mix once again and cook for 2 minutes. Afterwards, add turmeric, garam masala, chilli and coriander powder in the pan and toss lightly to incorporate the spices well with vegetables. Let the veggies cook for 2-3 minutes, then close the lid of the pan and lower the flame. Let the veggies cook for about 5 minutes.",
       "Step 5 Roll out the chapati:Meanwhile, unwrap the dough and divide it into 2-3 equal parts on a flat surface and make a ball of each. Using a little flour, roll these balls into the shape of a chapati.",
      "Step 6 Cook both sides of the chapati:Put a Tawa on medium flame and when it's mildly hot, carefully transfer the chapati on the heated Tawa. When tiny bubbles start to rise, flip it with a spatula and cook until both sides are golden brown. Apply a little oil on both sides and cook well. Put it aside and repeat the procedure to make more chapatis for the roll. By now, the veggies will be done, switch off the flame and transfer the veggies to a bowl.",
       "Step 7 Stuff the chapati with veggies to make the Kathi Rolls:Take chapati and apply a teaspoon of the green chutney evenly on one side. Then, add sufficient amount of cooked vegetables in the middle of the chapati. Garnish with some raw onion slices and chopped coriander leaves, and wrap it tightly to make a roll. Repeat to make more such Kathi rolls and serve hot!"],
},   
   {
    id:26,
    name:"Tomato Soup",
    image:"https://th.bing.com/th/id/OIP.Knjuaeypil2tVfmCyV1kUQHaJ4?w=200&h=267&c=7&r=0&o=5&dpr=1.5&pid=1.7",
    cooking_time:"Cooking Time: 40 mins",
    ingredients:["3 Cups Tomatoes chopped", "1 Carrot finely chopped","1 large Potato finely chopped", "1/4 tsp Black pepper powdered", "1 tsp Sugar", "2 Bread slicesTo fry the bread Oil","For garnishing Cream","2 tsp SaltWater"],
    method:["Put the tomatoes, carrot and potato to boil with 1 cup water and salt.",
        "2.Cook in a saucepan or a pressure cooker till the vegetables are completely cooked.",
        "3.Remove from fire and when cool enough to handle, strain the vegetables through a soup strainer or blend in a blender.",
        "4.Measure the liquid and add water to make up 4 1/2 cups.",
        "5.Bring to a boil again, and then simmer.",
        "6.Add sugar and black pepper.",
        "7.Simmer for another 10 minutes.",
        "8.While the soup is simmering, cut the bread into cubes and fry them in hot oil, till brown and crisp.",
        "9.Pour the soup in bowls, and garnish with the cream.",
        "10.Serve the croutons on the side."],
   },
   {
    id:27,
    name:"Tacos",
    image:"https://th.bing.com/th?id=OIF.3hZs%2f53x2GVndFju3zvIsA&w=197&h=197&c=7&r=0&o=5&dpr=1.5&pid=1.7",
    cooking_time:"Cooking Time : 25 mins",
    ingredients:["Ground beef (or other meat, see below)", "Canola oil or olive oil", "Tomato paste (or tomato sauce)", "Beef broth or water (you can also use chicken broth in a pinch)",
        "Diced tomatoes", "Fresh cilantro", "Chopped onions", "Cheese","Taco seasoning: chili powder, cumin, smoked paprika, dried oregano, garlic powder, sea salt, black pepper.",
        "Tortillas (corn tortilla or flour tortilla in taco size)", "Chopped avocado or guacamole", "Lime wedges (for squeezing on the tacos)", "Sour cream (optional)", "Salsa (optional)"],
    method:["Step 1: Cook the Ground Beef: Heat the oil in your skillet for two minutes over medium-high heat. You will add your meat once the oil is hot enough to sizzle.Add the ground beef to the skillet and stir as the meat cooks evenly and begins to brown. This process will take between 6-8 minutes. While the meat is browning, use a wooden spoon or potato masher to break the ground beef up into smaller pieces.",
        "Step 2: Add Seasoning: Once the meat is browned, add the beef broth, tomato paste, cumin, chili powder, oregano, garlic powder, sea salt, and black pepper to the skillet with the meat.Reduce the heat to medium and allow the meat mixture to simmer for about 3-5 minutes until the sauce becomes thick. Stir occasionally. When the sauce is thick, turn off the heat and set the skillet aside.",
        "Step 3: Heat the Tortillas:To heat your tortillas, put the tortillas one at a time into a hot ungreased skillet or cast-iron comal (the round Mexican flat skillet) for 30 seconds on each side.In a pinch, you can also heat your tortillas in the microwave. Another way to heat up your tortillas is to heat them directly on a gas burner for just a few seconds, allowing the edges to become slightly charred.",
        "Step 4: Assemble Your Tacos:For each tortilla, add about 2-3 tablespoons of your taco meat mixture. Top the ground beef mixture with onion, cheese, cilantro, and tomato.Add whatever other garnishes you want to your tacos, including sour cream, pico de gallo, or guacamole. Squeeze the lime wedges over your tortillas."],
   },
   {
    id:28,
    name:"Dal Tadka",
    image:"https://th.bing.com/th/id/OIP.MUO8Az1sRxWxVNIgqBbMzAHaJ4?w=219&h=202&c=7&r=0&o=5&dpr=1.5&pid=1.7",
    cooking_time:"Cooking Time : 30-45 mins",
    ingredients:["1 cup washed & dried moong dal","1 teaspoon ginger paste","1/2 teaspoon asafoetida","2 diced onion","1/2 teaspoon mustard seeds","3 sliced & slit green chilli",
        "1/2 teaspoon cumin seeds", "salt as required", "1 red chilli", "4 cup water", "4 cloves chopped garlic","5 tablespoon vegetable oil",
        "1 stalk curry leaves","1 teaspoon turmeric","2 finely chopped tomato","1/2 teaspoon fenugreek seeds","1 teaspoon red chilli powder."],
    method:[ "Cook moong dal in pressure cooker:To make this delicious Dal Tadka recipe, add moong dal in a pressure cooker. Add water and heat it over medium flame. Cook the dal for 2-3 whistles or until it gets quite mushy. After it's done, bring the flame to low and stir occasionally in between.  oil-in-pan-for-frying",
        "Step 2 Temper the spices in some oil.Now add oil to a pan and heat it over medium flame. Once the oil is sufficiently hot, add mustard seeds and dried red chilli to the pan. Once the seeds start to splutter, add asafoetida, turmeric, red chilli powder, ginger paste, garlic, fenugreek seeds, cumin seed, curry leave and green chillies.Saute-onions",
        "Step 3 Saute onion and tomato in the tempering: Then add chopped onions. Once the onions turn slightly pinkish in hue, add the chopped tomatoes to the pan and fry them along with the mixture for around 5-6 minutes on low-medium. Once done, add the mushy dal to the mixture. Then add salt as per your taste and stir well.",
        "Step 4 Add dal and simmer for 10 minutes: Simmer the dal on low-medium flame for 10 minutes or until the tomatoes become tender. Keep stirring occasionally. After few minutes, switch off the flame and transfer the dal to a serving bowl. Dal Tadka is ready to be served. Pair it with rice or chapatis along with a salad of your choice. You can also serve it with some crisp potato bites and raita."],
   },
   {
    id:29,
    name:"Shrimp Fajitas",
    image:"https://th.bing.com/th/id/OIP.33qv9Ol3AlPgUFOPA3p4cwHaLG?w=200&h=300&c=7&r=0&o=5&dpr=1.5&pid=1.7",
    cooking_time:"Cooking Time : 15-20 mins",
    ingredients:["Shrimp", "onion ", "bell peppers", "fajita seasoning", "olive oil", "cilantro and lime", "flour tortillas", "optional toppings."],
    method:["Step 1: Season the shrimpIn a large bowl, toss the shrimp with 2 tablespoons oil as well as the chili powder, garlic powder, salt, pepper, oregano and cumin.",
        "Step 2: Cook the fajita vegetables in a large skillet, heat the remaining 2 tablespoons oil over medium heat,Add the onion and peppers, Cook and stir until the vegetables are crisp-tender, five to seven minutes. Remove the vegetables from the pan.",
        "step 3: cook the shrimp , In the same pan, cook the shrimp over medium heat until the shrimp turn ink , two  to three minutes.",
        "step 4: Finish the fajitas, Add the cilantro and onion mixture to the pan , and heat through. REmove the pan from the heat. Cut one of the limes in GiHalfBodyCrawling. Squeeze one lime half over the shrimp mixture, Cut the remaining 1-1/2 limes into wedges for serving. Serve the shrimp mixture with tortillas and , if desired , the optional toppings.",
    ],
   },
   {
    id:30,
    name:"Mexican Chicken Soup",
    image:"https://th.bing.com/th/id/OIP.AUarZpY41dvO3pW4dJd6JwHaKB?w=200&h=271&c=7&r=0&o=5&dpr=1.5&pid=1.7",
    cooking_time:"Cooking Time : 1 hour",
    ingredients:["1 ¼ pounds skinless, boneless chicken breast halves", "2 tablespoons taco seasoning mix, divided", "1 tablespoon vegetable oil", "½ cup chopped onions", "½ cup chopped celery",
        "2 teaspoons ground cumin", "¼ teaspoon ground black pepper","3 (14 ounce) cans chicken broth"," 1 cup water", "1 cup diced tomatoes", "1 tablespoon chopped fresh cilantro",
        "Toppings: 1 cup shredded Cheddar cheese", "1 cup crushed tortilla chips","1 avocado - peeled, pitted and diced",],
    method:["Directions: Preheat the oven to 350 degrees F (175 degrees C).",
         "Lay chicken breasts evenly onto a baking sheet. Sprinkle with 1 tablespoon taco seasoning mix.",
         "Bake chicken in the preheated oven until no longer pink in the center and the juices run clear, 30 to 35 minutes. An instant-read thermometer inserted into the center should read at least 165 degrees F (74 degrees C). Allow to cool enough to handle, then shred or cut into strips.",
        "While chicken is cooking, warm oil in a stockpot over medium-high heat. Cook and stir onions and celery in hot oil until onion has softened and turned translucent, about 5 minutes. Stir in chicken broth and water; bring to a boil. Add remaining 1 tablespoon taco seasoning mix, cumin, and black pepper. Reduce heat to medium and simmer until flavors blend, about 30 minutes.",
        "Add chicken, tomatoes, and cilantro; simmer for 5 minutes. Serve soup hot topped with cheese, tortilla chips, and avocado."],
   },
   {
    id:31,
    name:"Bagara Egg Masala",
    image:"https://th.bing.com/th/id/OIP.7pCnrPDH5e9hmVQNMnizMgHaHa?w=188&h=188&c=7&r=0&o=5&dpr=1.5&pid=1.7",
    cooking_time:"Cooking Time : 25 mins",
    ingredients:["4 pcs Boiled Eggs","4 tsp Roasted Peanuts","2 tsp Sesame seeds","1 cup Coconut (Grated)","1 tsp Cumin seeds","1/2 tsp Fenugreek seeds","2 pcs Dry Red chillies","4 cloves Garlic (chopped)","4 pcs Curry leaves","2 pcs Green chillies","1 tsp Coriander Powder","1 tsp Turmeric powder","1 tsp Garam Masala","2 tsp Turmeric paste","to taste Salt","2 tsp Oil","1 cup water"],
    method:["Heat one tablespoon of oil in a pan and fry the boiled eggs for 2 minutes. Remove from pan and keep it aside.","2.Grind the peanuts, sesame seeds, coconut with a little water into a fine paste and keep it aside.","3.Heat oil in a pan. Add cumin seeds, fenugreek seeds, curry leaves, dry red chillies, garlic and green chillies one by one. Fry for a minute.","4.Now add the prepared paste of coconut, peanuts and sesame. Fry for 5 minutes on medium flame.","5.Add turmeric powder, cumin powder, coriander powder, salt and saute for 3-4 minutes.","6.Add water and mix well. Then add the eggs and tamarind paste. Lastly add garam masala powder and mix well.","7.Serve hot with steamed rice and a bowl of raita."],
   },
   {
    id:32,
    name:"Paneer Fried Rice",
    image:"https://th.bing.com/th/id/OIP.B-KpeAffBYsNkH0E-vRrVQHaE8?w=298&h=198&c=7&r=0&o=5&dpr=1.5&pid=1.7",
    cooking_time:"Cooking Time : 25 mins",
    ingredients:["1/2 Cup Boiled Rice","8-10 Paneer Cubes","1 tbsp Ginger garlic paste","1/2 tsp Red chilli powder","1/2 tsp Pepper","1 tsp Soya Sauce","Salt as per taste","1 Chopped Onion","1 Chopped Carrot","1/2 Chopped Capsicum","1/4 cup Chopped Mushroom"],
    method:["First, take boiled rice. Next, cut the paneer in small cubes, toss it in corn flour and fry them until crispy. Once done, heat a wok and add oil." ,
        "2.To this add ginger-garlic paste, then add fried paneer cubes. Let the flavours mix.",
        "3.Now throw in veggies life onion, carrots, capsicum and mushroom. Toss them well.",
        "4.Then add red chilli powder and pepper. Now add soy sauce and mix again.",
        "5.Check for salt, add as per your taste. Finally add the cooked rice and combine with everything.",
        "6.Serve hot in a bowl and enjoy!"],
   },
   {
    id:33,
    name:"Chicken Biryani",
    image:"https://th.bing.com/th/id/OIP.6aGaaREC61EZu8AvcsdOqwHaEK?w=256&h=187&c=7&r=0&o=5&dpr=1.5&pid=1.7",
    cooking_time:"Cooking Time : 1-1.5 hrs",
    ingredients:["1 cup boiled basmati rice","1/2 teaspoon mint leaves","salt as required","2 teaspoon virgin olive oil","3 green cardamom","2 clove","2 onion","1 teaspoon turmeric","1 tablespoon garlic paste","1 cup hung curd","2 tablespoon coriander leaves","water as required",
     "1 tablespoon ghee","600 gm chicken","1 tablespoon garam masala powder","1 teaspoon saffron","1 tablespoon bay leaf","1 black cardamom",
     "1 teaspoon cumin seeds","4 green chillies","1 tablespoon ginger paste","1 teaspoon red chilli powder","1/2 tablespoon ginger","2 drops kewra","1 tablespoon rose water"],
    method:["Step 1 Prepare saffron-kewra water and chop veggies:To make a delightful chicken biryani dish, firstly soak saffron in water to prepare saffron water (one tsp saffron can be soaked in 1/4 cup water). Next, mix kewra drops in water and mix well to make kewra water. Set them aside for later usage. Now, chop the onion and coriander leaves and keep them aside.",
            "Step 2 Saute the onions:Meanwhile, heat olive oil in a deep bottomed pan. Once the oil is hot enough, add cumin seeds, bay leaf, green cardamom, black cardamom, cloves in it, and saute for about a minute. Then, add chopped onion to it and saute until pink. Now, add chicken into it with slit green chillies, turmeric, salt to taste, ginger-garlic paste, red chilli powder and green chilli paste. Mix well all the spices and cook for 2-3 minutes. Then, add hung curd into it and give a mix. (Make sure the chicken is washed properly and patted dry before adding it to the dish)",
            "Step 3 Cook biryani on low heat for 5-6 minutes:Turn the flame to medium again and add garam masala in it along with ginger julienned, coriander and mint leaves. Add kewra water, rose water and 1 tsp saffron water in it. Cook till the chicken is tender. Then add 1 cup cooked rice and spread evenly. Then add the remaining saffron water and pour ghee over it. You can now cook the dish without the lid or cover it with a lid to give a dum-effect due to the steam formation.",
            "Step 4 Serve hot chicken biryani with your favourite chutney or raita: Cook for 15-20 minutes with a closed lid and garnish with 1 tbsp fried onions and coriander leaves. Serve hot chicken biryani with raita of your choice. Enjoy!"],
   },
   {
    id:34,
    name:"Turkish Chicken Kebab",
    image:"https://th.bing.com/th/id/OIP.XesnCyOmZ-MjW76Xs-I1xAHaE6?w=246&h=180&c=7&r=0&o=5&dpr=1.5&pid=1.7",
    cooking_time:"Cooking Time : 30-45 minutes (excluding marination time)",
    ingredients:["1 1/2 pounds boneless, skinless chicken breasts or thighs","1 large onion","2 cloves garlic","1/2 cup plain yogurt, or milk","3 tablespoons vegetable oil","2 tablespoons tomato paste","1 teaspoon freshly ground black pepper",
                "1 teaspoon paprika","1 teaspoon kosher salt, more to taste","Sumac, dried oregano, and paprika, for garnish, optional"],
    method:["1.Gather the ingredients.",
            "2.Pat 1 1/2 pounds bonelss, skinless chicken breasts dry with paper towels.",
            "3.Cut the meat into 1-inch pieces. Set aside.",
            "4.Using the finest grater possible, grate 1 large onion and 2 garlic cloves over a medium bowl.",
            "5.Pour the pulp and juice into a fine mesh strainer and, using a wooden spoon, press out the juice into a medium bowl. Discard the onion and garlic pulp; reserve the juice.",
            "6.Stir together the onion-garlic juice, 1/2 cup plain yogurt, 3 tablespoons vegetable oil, 2 tablespoons tomato paste, 1 teaspoon freshly ground black pepper, 1 teaspoon paprika, and 1 teaspoon kosher salt.",
            "7.Add the cubed chicken and toss to coat.",
            "8.Cover the bowl and refrigerate it for at least 4 hours, preferably overnight for maximum flavor.",
            "9.Prepare a medium (350°F to 375°F) gas or charcoal grill fire. If using bamboo skewers, soak skewers in water for 30 minutes so they don't catch fire on the grill.",
            "10.Remove the chicken pieces from the marinade and thread them onto soaked bamboo kebab skewers or metal skewers. The chunks of chicken can touch each other, but don’t put them too close together to ensure they cook through. Discard any remaining marinade.",
            "11.Sprinkle the kebabs generously with salt and place on pre heated grill. Grill evenly on all sides, about 12 minutes total.",
            "12.Garnish with sumac, dried oregano, and paprika, if desired, and serve."],
   },
   {
    id:35,
    name:"Lazagna",
    image:"https://th.bing.com/th/id/OIP.VyAzubaFqlNdzW4EAQar6AHaEc?w=228&h=181&c=7&r=0&o=5&dpr=1.5&pid=1.7",
    cooking_time:"Cooking Time: 2 hrs 30 mins",
    ingredients:["For the Bolognese Sauce:",
        "4 Bacon slices","2 medium Onions chopped","2 Garlic cloves  chopped","2 Carrots chopped","2 Celery sticks chopped", "Olive oil", "500 gram Lamb (minced)","2 Tomatoe tins","Sea salt","Pepper", "Handful Fresh basil", "For Lasagna:250 gram Lasagna pasta sheets1 large Tomato, sliced500 ml Fresh cream100 gram Parmesan cheese, grated"],
    method:["1.Put a pan on heat, add 4 strips of bacon and sprinkle some olive oil over it.","2.Fry the bacon for few minutes.", "3.Add garlic and fry till its golden.", "4.Add onion, carrots, celery, and cook until the mixture softens.", "5.Into this vegetable mixture add chopped basil stocks, chopped tomatoes, water, minced lamb, stir and bring it to boil.",
        "6.Season with salt and pepper.","7.Simmer the bolognese sauce for an hour and a half","8.To the sauce add 50 grams of parmesan cheese.","9.In a bowl whip the cream.", "10.In a baking tray layer the bolognese sauce, followed by lasagna sheets and whipped cream.",
        "11.Season the cream layer with Salt, pepper and oregano.","12.Repeat the layering process with the bolognese sauce, lasagna sheets and cream.","13.Top the last layer with grated parmesan cheese.",   "14.Top up with sliced tomatoes, basil leaves and sprinkle some olive oil on it", "15.Cover the tray with foil and bake in a 200°C preheated oven for 30 minutes.", "16.Remove the foil and bake for another 20 minutes.", "17.Serve hot."],
   },
   {
    id:36,
    name:"Garlic Shrimp",
    image:"https://th.bing.com/th/id/OIP.D3AzOwQqPiMTbcko0lGsCQHaFj?pid=ImgDet&w=177&h=132&c=7&dpr=1.5",
    cooking_time:"Cooking Time : 10-15 mins",
    ingredients:["Shrimp / Prawns.","Butter.","Fresh garlic.", "Chilli flakes.", "Cajun seasoning.","Salt and pepper.", "Cream. Heavy / Whipping cream.","Lemon juice.","Fresh parsley, for garnish.",],
    method:["1.Cook the shrimp: Pat the shrimp dry with paper towels then place in a bowl. Season generously with salt and pepper. Heat a large pan over high heat then add the butter and shrimp. Cook until they shrimp are opaque and starting to brown. Remove from the pan and set aside.",
            "2.Make the creamy garlic sauce: In the same pan, add another teaspoon of butter then add the garlic and the cajun seasoning. Pour the cream into the pan along with the lemon juice. Bring up to a simmer and cook for 5 minutes until the sauce has reduced and coats the back of a spoon easily.",
            "3.Combine and serve: Add the shrimp back into the pan then allow to heat through for 1-2 minutes. Scatter over the parsley and serve."],
   },
   {
    id:37,
    name:"Haleem",
    image:"https://img.freepik.com/premium-photo/picture-haleem_871710-27283.jpg",
    cooking_time:"Cooking Time : 2 hrs 30 mins",
    ingredients:["1/2 tsp lamb (boneless)","150 gms moong dal (washed)","50 gms dal chana","100 gms wheat (broken)","500 ml desi ghee","10 Cloves",",4 Bay leaves","1 gms saffron","30 gms green chilly paste","10 gms turmeric powder","6 gms mace","10 gms green cardamom","50 gms garlic paste","50 gms ginger grated","150 gms onion fried","3-4 litre lamb stock","to taste salt"],
    method:["1.Wash and soak all the lentils and broken wheat together for 2 hours.","2.Take a heavy bottom handi and add ghee to temper it with whole spices - cloves, bay leaf and green cardamom. When the spices start crackling, add the grated ginger and garlic paste till the colour turns brown.",
        "3.Add the lamb along with all the powdered spices saffron, green chilli paste, turmeric powder and cook until it is half done and then add fried onions.","4.Drain the water from the lentils and add it to the lamb along with lamb stock. Add salt at this stage.","5.Let it cook until lamb gets tender and mixes with the lentils and becomes thick in consistency.","6.Check for the seasoning and serve with the choice of breads"],
   },
   {
    id:38,
    name:"Chicken Pizza",
    image:"https://th.bing.com/th/id/OIP.lNdhCmvJvNK4-_z_pMaRbwHaHa?w=200&h=200&c=7&r=0&o=5&dpr=1.5&pid=1.7",
    cooking_time:"Cooking Time : 40 mins",
    ingredients:["1 Tbsp Chili or sunflower oil2 Boneless and skinless chicken breasts (cut into 1/2-inch pieces)1 tsp Root ginger (grated), peeled3-4 Garlic cloves, finely chopped4-5 tbsp Pasta sauce or 2 tomatoes (chopped and blended)1 tbsp Chili and garlic sauce1 tsp Soy sauce1/4 tsp Chili powder1 Readymade pizza base or a garlic pizza flatbread, 10-12 inches in diameter1/2 Red onion, sliced30 gram Cheddar cheese, gratedA small handful fresh coriander leaves, chopped"],
    method:["1.Preheat the oven to 200C.","2.Heat the oil on a medium heat in a frying pan or wok. Add the chicken and fry for 8 to 10 minutes.","3.Tip in the ginger and garlic and mix for a couple of minutes. Stir in the pasta sauce or tomatoes and soy sauce. Mix in the chili powder.","4.Spoon the mixture onto the pizza base. Sprinkle with the onion and cheese.","5.Bake for 10 minutes until the cheese has melted. Serve hot."],
   },
   {
    id:39,
    name:"Alfredo Pasta",
    image:"https://th.bing.com/th/id/OIP.uZeoa3JxxEho0vVj6VqDgAHaIt?w=200&h=236&c=7&r=0&o=5&dpr=1.5&pid=1.7",
    cooking_time:"Cooking Time: 30-35 mins",
    ingredients:["12 oz (340g) Penne pasta","6 tbsp (84g) unsalted butter","6 cloves garlic, minced","1 cup (250ml) heavy cream","1 cup (250g) grated Parmesan cheese","Salt and black pepper, to taste","Fresh parsley, chopped (optional)"],
    method:["1.Bring a large pot of salted water to a boil and cook the penne pasta according to the package instructions until al dente. Drain and set aside.",
            "2.In a large saucepan, melt the butter over medium heat. Add the minced garlic and cook for 1-2 minutes, until fragrant.",
            "3.Pour in the heavy cream and bring the mixture to a simmer. Let it cook for 2-3 minutes, until the cream has thickened slightly.",
            "4.Remove the saucepan from the heat and stir in the Parmesan cheese until melted and smooth. Season with salt and black pepper to taste.",
            "5.Add the cooked penne pasta to the cheese sauce and toss until the pasta is well coated.",
            "6.Serve immediately, garnished with chopped fresh parsley if desired."],
   },
   {
    id:40,
    name:"Crispy Fried Chicken ",
    image:"https://th.bing.com/th/id/OIP.cr-57g8ORTQ7DPpuEG2gPAHaFj?w=248&h=187&c=7&r=0&o=5&dpr=1.5&pid=1.7",
    cooking_time:"Cooking Time : 1 hr 15 mins",
    ingredients:["Chicken (bone-in pieces are ideal): 1 kg (thighs, drumsticks, or wings)","Buttermilk: 2 cups","All-Purpose Flour: 2 cups","Cornstarch: ½ cup (for extra crispiness)","Salt: 1 teaspoon.","Pepper: 1 teaspoon.","Garlic Powder: 1 tsp","Onion Powder: 1 tsp","Paprika: 1 teaspoon","Cayenne Pepper: ½ tsp (optional, for heat)","Eggs: 2, beaten",
                    "Oil for Frying (like canola or vegetable oil): Enough to submerge the chicken pieces"],
    method:["1. Marinate in Buttermilk:Buttermilk tenderizes the chicken, making it juicy and full of flavor.Place the chicken pieces in a large bowl and pour the buttermilk over them.Add a pinch of salt and pepper, cover the bowl, and refrigerate for at least 2 hours (or overnight for best results).",
            "2. Prepare the CoatingThe coating is the secret to that satisfying crunch.In a large bowl, mix the flour, cornstarch, salt, pepper, garlic powder, onion powder, paprika, and cayenne pepper.In a separate bowl, beat the eggs for an egg wash, which helps the coating stick better.",
            "3. Coat the Chicken;To achieve a thick, crunchy crust:Remove the chicken from the buttermilk marinade, letting any excess drip off.Dip each piece into the flour mixture, then into the egg wash, and finally back into the flour mixture for a double layer of coating.Set the coated chicken aside on a wire rack for 10-15 minutes to let the coating adhere.",
            "4. Heat the Oil:To achieve perfect crispiness, use oil that maintains a high, steady temperature.In a heavy skillet or deep fryer, heat the oil to 350°F (175°C). Maintaining this temperature is crucial to avoid greasy or undercooked chicken.Use a thermometer if you have one; otherwise, test with a small piece of coating—if it bubbles immediately and floats, the oil is ready.",
            "5. Fry the Chicken,Now it’s time to fry:Fry the chicken in batches to avoid crowding, which can lower the oil temperature.Cook each piece for 12–15 minutes, turning occasionally, until golden brown and crispy. Use a meat thermometer to ensure the internal temperature reaches 165°F (74°C).Remove each piece with a slotted spoon and drain on paper towels or a wire rack.",
            "6. Let it Rest:Resting allows the coating to crisp up even more.After removing the chicken from the fryer, let it rest for a few minutes. This will give the crust time to firm up while keeping the inside juicy."],
   },
   {
    id:41,
    name:"Veg Noodles",
    image:"https://th.bing.com/th/id/OIP.pUOuSrojGePDztjY8HhzUAHaHa?w=200&h=200&c=7&r=0&o=5&dpr=1.5&pid=1.7",
    cooking_time:"Cooking Time : 30 mins",
    ingredients:["Noodles","Veggies","Sauce","Oil"],
    method:["1.Boil 4 cups water along with salt and oil.",
        "2.Add 150 grams noodles. I broke into half and added.",
        "3.Cook it until slightly soft but not mushy.",
        "4.It should be al-dente – just cooked. I cooked for 5 mins and it was perfect.But follow pack instructions for cooking time.",
        "5.Drain water.",
        "6.Rinse with cold water to remove the excess starch and stop further cooking.",
        "7.Add little oil, toss it and keep aside to avoid sticking to each other.",
        "8.To a large wok – Heat 2 tablespoon oil first add 2 teaspoon garlic finely chopped along with 1 teaspoon spring onion white part and 1/2 teaspoon ginger(optional). Saute for 2 mins.",
        "9.Add 1/4 sliced onion, 1/2 cup carrot, 1/2 cup capsicum, 3/4 cup cabbage.",
        "10.Saute for 2 mins in medium high heat – Make sure the veggies should be crunchy.",
        "11.Keep heat in high flame – Add 1 teaspoon soya sauce, 1 teaspoon chilli sauce, 1/2 teaspoon sugar, 1 teaspoon vinegar, salt to taste and 1 teaspoon pepper powder.",
        "12.Give a quick toss so that the veggies are coated with sauces, it should be done in high heat so be quick.",
        "13.Finally add cooked noodles along with 1 tablespoon spring onion green part.",
        "14.Mix it well. Add 1/2 teaspoon crushed pepper. Using 2 ladles was very easy to mix.",
        "15.Toss it well in high flame.If you are able to carry the wok toss it well to get a mild smokey flavor just like in restaurants.",
        "Noodles is ready!" ],
   },
   {
    id:42,
    name:"Cream Of Chicken Soup",
    image:"https://th.bing.com/th/id/OIP.Ek0m6mBR9ckv2RXaj3rWMgHaIa?w=200&h=227&c=7&r=0&o=5&dpr=1.5&pid=1.7",
    cooking_time:"Cooking time : 30 mins",
    ingredients:["1 tbsp olive oil","3.5 tbsp unsalted butter","½ cup flour","1 garlic clove minced","½ small brown onion finely chopped","1 small carrot diced","½ red capsicum/bell pepper finely chopped",
                 "1 small celery stick diced","500 ml chicken stock/broth preferably low sodium","750 ml Milk","½ tsp salt","¼ tsp Garlic Powder","¼ tsp onion powder",
                 "¼ tsp Dried Thyme","¼ tsp black pepper","¾ cup frozen peas","1 cup cooked chicken breasts diced or shredded"],
    method:["Take a large, deep-bottomed pan. Add some oil in the pan and heat it over medium-high flame. Then add onion and garlic to the pan and sauté for 2 minutes. Let the onion turn translucent. The garlic should turn aromatic. Then add the vegetables such as carrots, celery and capsicum. Sauté the vegetables for a minute. Let the vegetables soften.",
            "Add some butter to the pan and let it melt. Then add the flour until it is mixed. Keep stirring for a minute. Then add the chicken broth and stir until the flour is completely mixed. Add the milk and keep stirring.",
            "Add garlic powder, onion powder and dried thyme to the mixture. Give it a stir and let it thicken.",
            "Add the cooked chicken and peas and give the soup a good stir. Bring it to a simmer and let it bubble. Once the soup has thickened as per your preference, add salt and pepper and give it a stir. Add some croutons, garnish with thyme and serve hot."],
   },
   {
    id:43,
    name:"Butter Chicken",
    image:"https://th.bing.com/th/id/OIP.QQLjswYhkCZemRyvqftt4QAAAA?w=200&h=200&c=7&r=0&o=5&dpr=1.5&pid=1.7",
    cooking_time:"Cooking Time : 50 mins",
    ingredients:["For the marinade:","Raw Chicken","2 tsp Red Chilli Powder","2 tsp Ginger-Garlic Paste","2 tsp Salt","2 tsp Lemon Juice","1/2 cup Curd","1/2 tsp Garam Masala","1 tsp Kasuri Methi","2 tsp Mustard Oil","For gravy:","2 tsp Oil","2 to taste Butter Cubes","3 gram Cloves","1 Cinnamon Stick sliced","1 tsp Mace","7 Cardamom","4 Tomatoes chopped","1 tsp Garlic","1 tsp Ginger","1 tsp Ginger-Garlic Paste","1 1/2 tsp Red Chilli Powder","1 tsp Kasuri Methi","2 tsp Honey","1 Green Chilli","2 tsp Cardamom Powder","1 tbsp Cream"],
    method:["For marination:","1.In a mixing bowl, put raw chicken pieces and add salt, red chilli powder, ginger garlic paste and lemon juice. Mix well.","2.Refrigerate for about 15-20 minutes.Butter Chicken",
        "3.Now add curd to the refrigerated mix. Followed by salt, ginger garlic paste, red chilli powder, garam masala, kasuri methi and mustard oil. Mix well and refrigerate again for an hour.","4.Roast the marinated chicken in an oven for about 30 minutes until it is three-fourth done.",
        "Prepare the chicken gravy:1.Heat 2 tsp of oil in a pan with butter.","2.Add cloves, cinnamon stick, mace and cardamom. Saute and then add chopped tomatoes, garlic and ginger. Mix well and then grind well.3.In another pan, heat another two cubes of butter, along with ginger garlic paste.",
        "4.Add the tomato puree made from the mixture. Now add red chilli powder, kasuri methi, honey and finally the roasted chicken pieces. Let it simmer.5.Add green chilli, cardamom powder and cream. Mix well.6.Serve with a teaspoon of cream over."],
   },
   {
    id:44,
    name:"Paneer Butter Masala",
    image:"https://th.bing.com/th/id/OIP.RtehcxyUU2F8eQIe-Hxn1AHaJQ?w=200&h=250&c=7&r=0&o=5&dpr=1.5&pid=1.7",
    cooking_time:"Cooking Time: 40-45 mins",
    ingredients:["250 gm paneer","1/2 teaspoon garlic paste","1 1/2 tablespoon cashew nut paste","3 tablespoon fresh cream","2 tablespoon butter",
                "1 teaspoon kasoori methi powder","1 teaspoon chaat masala powder","1 cup tomato puree","1/2 teaspoon ginger paste","1/2 teaspoon red chilli powder","1 tablespoon ghee","salt as required","1/2 teaspoon honey"],
    method:["Step 1 Prepare the tomato-cashew nut gravy:To prepare this easy paneer recipe, take a pan and melt ghee in it. Once the ghee is melted, add ginger garlic paste and saute these ingredients for half a minute. Then add tomato puree to it. Stir well and then add cashew nut paste along with red chilli powder and salt. Mix well and cook for 2 minutes.",
            "Step 2 Cook paneer in this gravy for 2 minutes: Now, add honey, kasoori methi powder, butter in the gravy and mix well. Cook for 2-3 minutes and then add paneer pieces to it. Stir gently and coat the gravy well over the paneer pieces.",
            "Step 3 Garnish with fresh cream and serve Paneer Butter Masala hot: Add fresh cream (keep 1 tbsp aside) in the gravy along with 1/2 tsp chaat masala. Cook for 2-3 minutes. Your Paneer Butter Masala is ready! Garnish with remaining fresh cream and chaat masala. Serve Paneer Butter Masala hot with paratha, rotis or rice!"],
   },
   {
    id:45,
    name:"Mutton Rogan Josh",
    image:"https://th.bing.com/th/id/OIP.w2OXF3i_yQjhPwBWnfwiPwHaHa?w=175&h=180&c=7&r=0&o=5&dpr=1.5&pid=1.7",
    cooking_time:"Cooking Time : 1-1.5 hrs",
    ingredients:["1 kilograms chopped into cubes mutton", "1/2 teaspoon asafoetida","2 cinnamon","5 black cardamom","1 1/4 teaspoon ginger powder","150 gm hung curd","salt as required",
                 "1 1/2 cup water","2 1/2 tablespoon milk","1/2 cup ghee","1 1/4 teaspoon cumin seeds","1 teaspoon peppercorns","4 red chilli","1 1/4 tablespoon coriander powder",
                 "2 pinch saffron","1 tablespoon red chilli powder","1 1/2 tablespoon fennel seeds powder","1 1/4 tablespoon"],
    method:["Step 1 Saute the whole spices in ghee and prepare saffron milk:To prepare this delicacy, first, prepare the saffron milk by soaking saffron in milk. Next, put a pressure cooker and heat ghee in it. When the ghee is hot enough, add the whole spices and fry for a few seconds.",
            "Step 2 Cook mutton with the whole spices.Then, add whole red chillies, cumin seeds and asafoetida in the pressure cooker and fry for a few seconds. Afterwards, add the mutton pieces in it and stir well. Cover with the lid but don’t close it and cook the mutton for 5-6 minutes on medium to high flame. You will notice the meat will turn light brown in colour. After 5 minutes, remove the lid and add 1/2 cup of water in it and stir well with the spices. This will help the mutton in soaking the flavours of all the spices. Then, lower the flame and cook the mutton for 10-15 minutes.",
            "Step 3 Mix yoghurt with saffron milk and other spices. Meanwhile, take a small bowl and add all-purpose flour along with yoghurt in it, mix well. In this yoghurt mixture, add saffron milk (step 1), salt, fennel powder, coriander powder, Kashmiri red chilli powder and dry ginger powder (sonth powder). Mix all the spices well in the yoghurt. Once done, add into the pressure cooker. Stir well using a ladle and cook the mutton in yoghurt for at least a minute.",
            "Step 4 Add this yoghurt mixture in pressure cooker and slow cook the mutton for 1-2 hours.Then, add 1 cup of water in the pressure cooker and slow cook the mutton for 1-2 hours. Stir in between so that it doesn’t stick to the bottom. You can also pressure cook the mutton for 5-6 whistles. Once done, garnish and serve hot with chapati or naan. You can also enjoy this dish with rice."],
   },
   {
    id:46,
    name:"Aloo Gobi",
    image:"https://th.bing.com/th/id/OIP.jQgxtzBbhE93qRDkwEkFigHaHa?w=170&h=180&c=7&r=0&o=5&dpr=1.5&pid=1.7",
    cooking_time:"Cooking Time : 25-30 mins",
    ingredients:["700 Gram cauliflower","2 pieces potatoes large","200 gram fresh fenugreek","4 tbsp mustard oil","1 tsp black mustard seeds","1 tsp cumin seeds","12 curry leaves blanched","5 gram ginger finely chopped","to taste salt","2 medium green chillies finely chopped","1 tsp lemon juice","1 tsp mango powder", "peeled30 gram fresh pomegranate"],
    method:["1.Heat oil in a pan and add the chopped onions. When the onions turn soft, add the ginger and garlic and saute until fragrant (about 2 mins).",
            "2.Add the potatoes and cauliflower to this and cook on lowest heat, covered, mixing now and then so the vegetable pieces don't burn.",
            "3.When the vegetables are half cooked, add the tomato paste and mix again. Cook again for 3-4 mins or until the vegetables are soft (not mushy).",
            "4.Add the spice powders - coriander powder, turmeric powder, cumin powder, and chilli powder. Mix again until well combined. Cook until the spice powders don't smell raw anymore - another 2 mins or so. The potatoes and cauliflower should be roasted and dry by now. Add salt.",
            "5.Finish off with garam masala and a generous amount of chopped coriander leaves and mix again."],
   },
   {
    id:47,
    name:"Veg Pulao",
    image:"https://th.bing.com/th/id/OIP.Hb9JRHggPEWv4toQ0jpxcQHaHa?w=196&h=197&c=7&r=0&o=5&dpr=1.5&pid=1.7",
    cooking_time:"Cooking Tiem : 25-35 mins",
    ingredients:["Spices", "Ginger garlic Paste","Herbs","Rice","Mixed Vegetables,"],
    method:["Stovetop Method:Sauté whole spices, add ginger garlic paste, and sauté vegetables.", "Add rice and sauté briefly, then pour water.","Cook until rice is fluffy and fully cooked.",
            "Instant Pot Method:Sauté whole spices and ginger garlic paste using the sauté function.","Add vegetables, rice, and water. Pressure cook until done."],
   },
   {
    id:48,
    name:"Sarson Ka Saag",
    image:"https://th.bing.com/th/id/OIP.9tUcf3dNUShUlWMKa8j9cQHaFs?w=216&h=180&c=7&r=0&o=5&dpr=1.5&pid=1.7",
    cooking_time:"Cooking Time : 30 mins",
    ingredients:["500 grams Mustard greens , washed and roughly chopped","250 grams Spinach Leaves (Palak) , washed and roughly chopped","250 grams Bathua leaves , washed and roughly chopped",
                 "100 grams Methi Leaves (Fenugreek Leaves) , washed and roughly chopped","For Flavour & Taste","3 tablespoons Ghee","2 inch Ginger , finely chopped",
                 "8 cloves Garlic , finely chopped","1 Onion , finely chopped","4 Green Chillies , finely chopped","1 Tomato , finely chopped","1 teaspoon Makki Ka Atta (Yellow Corn Meal Flour)",
                 "Salt , to taste","Tempering","1 tablespoon Ghee","1 teaspoon Cumin seeds (Jeera)","3 cloves Garlic , finely chopped","1 Dry Red Chilli"],
    method:["To begin making the Sarson Ka Saag Recipe, we will first steam the leaves together along with a little salt until soft and yet green. For this, you can use a steamer or a pressure cooker.",
            "Traditionally it is chopped and cooked in a pan for about one hour. But I really like the pressure cooking method, as it fastens the process and maintains the rich green colour of the greens and nutrition as well. ",
            "Place all the leaves in the pressure cooker, add a little salt and 1/4 cup of water. Cover the pressure cooker and cook until you hear one whistle. After the first whistle turn off the heat.",
            "Release the pressure immediately. This process of releasing the pressure immediately will help keep the greens green.",
            "Allow it to cool. Mash the saag with a masher to make it mushy. You can either puree the saag or use a masher and mish mash the greens to make it soft and mushy. The way you like to present it is purely your choice.",
            "Heat a teaspoon of ghee in a heavy bottomed pan; add the ginger, garlic, onions and green chillies. Saute all the ingredients together on low heat until the onions are completely tender and soft and lightly browned.",
            "Once the onions are well softened, stir in the steamed sarson ka saag, salt and makki ka atta.",
            "Simmer the saag in the onion, ginger, garlic, green chilli mixture for 10 to 12 minutes, so that the greens get the flavours from the spices and onions. Turn off the heat, check the salt and adjust to taste accordingly. Transfer this to serving bowl.",
            "Finally, in another small pan; heat ghee over medium heat for tempering. Add the cumin seeds, garlic and the red chillies, saute until the garlic get a roasted texture. Pour this seasoning over the sarson ka saag and serve hot. Serve the Sarson Ka Saag along with Makki Ki Roti or Kulcha with a dollop of white butter and jaggery and end it with a Masala Chaas."],
   },
];
